import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import HomePage from '@/components/HomePage';

const Home: NextPage = (props) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mx-2 sm:mx-5 md:mx-10">
        <HomePage />
      </div>
    </div>
  );
};

export default Home;
